spring:
  application:
    name: SysM
  jmx:
    enabled: false

server:
  servlet:
    context-path: /
  port:
    8080

app:
  version: "@project.version@"

allowed:
  origins:
    - http://localhost:5500
    - http://127.0.0.1:5500
